package mcvc.hibernate.clases;
// Generated 06-16-2012 08:39:39 AM by Hibernate Tools 3.2.1.GA



/**
 * TblBoardId generated by hbm2java
 */
public class TblBoardId  implements java.io.Serializable {


     private String brdTabId;
     private int clsId;

    public TblBoardId() {
    }

    public TblBoardId(String brdTabId, int clsId) {
       this.brdTabId = brdTabId;
       this.clsId = clsId;
    }
   
    public String getBrdTabId() {
        return this.brdTabId;
    }
    
    public void setBrdTabId(String brdTabId) {
        this.brdTabId = brdTabId;
    }
    public int getClsId() {
        return this.clsId;
    }
    
    public void setClsId(int clsId) {
        this.clsId = clsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblBoardId) ) return false;
		 TblBoardId castOther = ( TblBoardId ) other; 
         
		 return ( (this.getBrdTabId()==castOther.getBrdTabId()) || ( this.getBrdTabId()!=null && castOther.getBrdTabId()!=null && this.getBrdTabId().equals(castOther.getBrdTabId()) ) )
 && (this.getClsId()==castOther.getClsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBrdTabId() == null ? 0 : this.getBrdTabId().hashCode() );
         result = 37 * result + this.getClsId();
         return result;
   }   


}


