package mcvc.hibernate.clases;
// Generated 06-10-2012 11:18:36 AM by Hibernate Tools 3.2.1.GA



/**
 * TblBoard generated by hbm2java
 */
public class TblBoard  implements java.io.Serializable {


     private Integer brdId;
     private TblSession tblSession;
     private String brdName;
     private byte[] brdText;

    public TblBoard() {
    }

	
    public TblBoard(TblSession tblSession, String brdName) {
        this.tblSession = tblSession;
        this.brdName = brdName;
    }
    public TblBoard(TblSession tblSession, String brdName, byte[] brdText) {
       this.tblSession = tblSession;
       this.brdName = brdName;
       this.brdText = brdText;
    }
   
    public Integer getBrdId() {
        return this.brdId;
    }
    
    public void setBrdId(Integer brdId) {
        this.brdId = brdId;
    }
    public TblSession getTblSession() {
        return this.tblSession;
    }
    
    public void setTblSession(TblSession tblSession) {
        this.tblSession = tblSession;
    }
    public String getBrdName() {
        return this.brdName;
    }
    
    public void setBrdName(String brdName) {
        this.brdName = brdName;
    }
    public byte[] getBrdText() {
        return this.brdText;
    }
    
    public void setBrdText(byte[] brdText) {
        this.brdText = brdText;
    }




}


