package mcvc.hibernate.clases;
// Generated 06-16-2012 08:39:39 AM by Hibernate Tools 3.2.1.GA



/**
 * TblEstudiantesxclase generated by hbm2java
 */
public class TblEstudiantesxclase  implements java.io.Serializable {


     private TblEstudiantesxclaseId id;
     private TblSession tblSession;
     private TblUsuarios tblUsuarios;
     private Character excNota;
     private Integer excCantParticipaciones;

    public TblEstudiantesxclase() {
    }

	
    public TblEstudiantesxclase(TblEstudiantesxclaseId id, TblSession tblSession, TblUsuarios tblUsuarios) {
        this.id = id;
        this.tblSession = tblSession;
        this.tblUsuarios = tblUsuarios;
    }
    public TblEstudiantesxclase(TblEstudiantesxclaseId id, TblSession tblSession, TblUsuarios tblUsuarios, Character excNota, Integer excCantParticipaciones) {
       this.id = id;
       this.tblSession = tblSession;
       this.tblUsuarios = tblUsuarios;
       this.excNota = excNota;
       this.excCantParticipaciones = excCantParticipaciones;
    }
   
    public TblEstudiantesxclaseId getId() {
        return this.id;
    }
    
    public void setId(TblEstudiantesxclaseId id) {
        this.id = id;
    }
    public TblSession getTblSession() {
        return this.tblSession;
    }
    
    public void setTblSession(TblSession tblSession) {
        this.tblSession = tblSession;
    }
    public TblUsuarios getTblUsuarios() {
        return this.tblUsuarios;
    }
    
    public void setTblUsuarios(TblUsuarios tblUsuarios) {
        this.tblUsuarios = tblUsuarios;
    }
    public Character getExcNota() {
        return this.excNota;
    }
    
    public void setExcNota(Character excNota) {
        this.excNota = excNota;
    }
    public Integer getExcCantParticipaciones() {
        return this.excCantParticipaciones;
    }
    
    public void setExcCantParticipaciones(Integer excCantParticipaciones) {
        this.excCantParticipaciones = excCantParticipaciones;
    }




}


