package mcvc.hibernate.clases;
// Generated Dec 10, 2011 10:08:36 AM by Hibernate Tools 3.2.1.GA



/**
 * TblEstudiantesxclaseId generated by hbm2java
 */
public class TblEstudiantesxclaseId  implements java.io.Serializable {


     private String excEstudiante;
     private int excClase;

    public TblEstudiantesxclaseId() {
    }

    public TblEstudiantesxclaseId(String excEstudiante, int excClase) {
       this.excEstudiante = excEstudiante;
       this.excClase = excClase;
    }
   
    public String getExcEstudiante() {
        return this.excEstudiante;
    }
    
    public void setExcEstudiante(String excEstudiante) {
        this.excEstudiante = excEstudiante;
    }
    public int getExcClase() {
        return this.excClase;
    }
    
    public void setExcClase(int excClase) {
        this.excClase = excClase;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TblEstudiantesxclaseId) ) return false;
		 TblEstudiantesxclaseId castOther = ( TblEstudiantesxclaseId ) other; 
         
		 return ( (this.getExcEstudiante()==castOther.getExcEstudiante()) || ( this.getExcEstudiante()!=null && castOther.getExcEstudiante()!=null && this.getExcEstudiante().equals(castOther.getExcEstudiante()) ) )
 && (this.getExcClase()==castOther.getExcClase());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getExcEstudiante() == null ? 0 : this.getExcEstudiante().hashCode() );
         result = 37 * result + this.getExcClase();
         return result;
   }   


}


