package mcvc.hibernate.clases;
// Generated 06-16-2012 08:39:39 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * TblLog generated by hbm2java
 */
public class TblLog  implements java.io.Serializable {


     private Integer logId;
     private TblUsuarios tblUsuarios;
     private Date logFecha;
     private String logMensaje;

    public TblLog() {
    }

    public TblLog(TblUsuarios tblUsuarios, Date logFecha, String logMensaje) {
       this.tblUsuarios = tblUsuarios;
       this.logFecha = logFecha;
       this.logMensaje = logMensaje;
    }
   
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    public TblUsuarios getTblUsuarios() {
        return this.tblUsuarios;
    }
    
    public void setTblUsuarios(TblUsuarios tblUsuarios) {
        this.tblUsuarios = tblUsuarios;
    }
    public Date getLogFecha() {
        return this.logFecha;
    }
    
    public void setLogFecha(Date logFecha) {
        this.logFecha = logFecha;
    }
    public String getLogMensaje() {
        return this.logMensaje;
    }
    
    public void setLogMensaje(String logMensaje) {
        this.logMensaje = logMensaje;
    }




}


