package mcvc.hibernate.clases;
// Generated 06-16-2012 08:39:39 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TblUsuarios generated by hbm2java
 */
public class TblUsuarios  implements java.io.Serializable {


     private String usrEmail;
     private String usrNombres;
     private String usrPrimerApellido;
     private String usrCelular;
     private String usrTelefono;
     private String usrPassword;
     private String usrSegundoApellido;
     private boolean usrStatus;
     private Set tblLogs = new HashSet(0);
     private Set tblEstudiantesxclases = new HashSet(0);

    public TblUsuarios() {
    }

	
    public TblUsuarios(String usrEmail, String usrNombres, String usrPrimerApellido, String usrPassword, String usrSegundoApellido, boolean usrStatus) {
        this.usrEmail = usrEmail;
        this.usrNombres = usrNombres;
        this.usrPrimerApellido = usrPrimerApellido;
        this.usrPassword = usrPassword;
        this.usrSegundoApellido = usrSegundoApellido;
        this.usrStatus = usrStatus;
    }
    public TblUsuarios(String usrEmail, String usrNombres, String usrPrimerApellido, String usrCelular, String usrTelefono, String usrPassword, String usrSegundoApellido, boolean usrStatus, Set tblLogs, Set tblEstudiantesxclases) {
       this.usrEmail = usrEmail;
       this.usrNombres = usrNombres;
       this.usrPrimerApellido = usrPrimerApellido;
       this.usrCelular = usrCelular;
       this.usrTelefono = usrTelefono;
       this.usrPassword = usrPassword;
       this.usrSegundoApellido = usrSegundoApellido;
       this.usrStatus = usrStatus;
       this.tblLogs = tblLogs;
       this.tblEstudiantesxclases = tblEstudiantesxclases;
    }
   
    public String getUsrEmail() {
        return this.usrEmail;
    }
    
    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail;
    }
    public String getUsrNombres() {
        return this.usrNombres;
    }
    
    public void setUsrNombres(String usrNombres) {
        this.usrNombres = usrNombres;
    }
    public String getUsrPrimerApellido() {
        return this.usrPrimerApellido;
    }
    
    public void setUsrPrimerApellido(String usrPrimerApellido) {
        this.usrPrimerApellido = usrPrimerApellido;
    }
    public String getUsrCelular() {
        return this.usrCelular;
    }
    
    public void setUsrCelular(String usrCelular) {
        this.usrCelular = usrCelular;
    }
    public String getUsrTelefono() {
        return this.usrTelefono;
    }
    
    public void setUsrTelefono(String usrTelefono) {
        this.usrTelefono = usrTelefono;
    }
    public String getUsrPassword() {
        return this.usrPassword;
    }
    
    public void setUsrPassword(String usrPassword) {
        this.usrPassword = usrPassword;
    }
    public String getUsrSegundoApellido() {
        return this.usrSegundoApellido;
    }
    
    public void setUsrSegundoApellido(String usrSegundoApellido) {
        this.usrSegundoApellido = usrSegundoApellido;
    }
    public boolean isUsrStatus() {
        return this.usrStatus;
    }
    
    public void setUsrStatus(boolean usrStatus) {
        this.usrStatus = usrStatus;
    }
    public Set getTblLogs() {
        return this.tblLogs;
    }
    
    public void setTblLogs(Set tblLogs) {
        this.tblLogs = tblLogs;
    }
    public Set getTblEstudiantesxclases() {
        return this.tblEstudiantesxclases;
    }
    
    public void setTblEstudiantesxclases(Set tblEstudiantesxclases) {
        this.tblEstudiantesxclases = tblEstudiantesxclases;
    }




}


